
package demo.mtom.streamsending.client.stubs;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue May 08 16:54:51 CEST 2012
 * Generated source version: 2.3.1
 * 
 */

public final class Blobconsumer_BlobconsumerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.streamreceiving.mtom.demo/", "WSBeanService");

    private Blobconsumer_BlobconsumerPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = WSBeanService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WSBeanService ss = new WSBeanService(wsdlURL, SERVICE_NAME);
        Blobconsumer port = ss.getBlobconsumerPort();  
        
        {
        System.out.println("Invoking echo...");
        java.lang.String _echo_arg0 = "";
        java.lang.String _echo__return = port.echo(_echo_arg0);
        System.out.println("echo.result=" + _echo__return);


        }
        {
        System.out.println("Invoking feedMe...");
        demo.mtom.streamsending.client.stubs.BigDataRequest _feedMe_arg0 = null;
        try {
            java.lang.String _feedMe__return = port.feedMe(_feedMe_arg0);
            System.out.println("feedMe.result=" + _feedMe__return);

        } catch (IOException_Exception e) { 
            System.out.println("Expected exception: IOException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
