package demo.mtom.streamsending.client.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue May 08 16:54:52 CEST 2012
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://server.streamreceiving.mtom.demo/", name = "Blobconsumer")
@XmlSeeAlso({ObjectFactory.class})
public interface Blobconsumer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://server.streamreceiving.mtom.demo/", className = "demo.mtom.streamsending.client.stubs.Echo")
    @WebMethod
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://server.streamreceiving.mtom.demo/", className = "demo.mtom.streamsending.client.stubs.EchoResponse")
    public java.lang.String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "feedMe", targetNamespace = "http://server.streamreceiving.mtom.demo/", className = "demo.mtom.streamsending.client.stubs.FeedMe")
    @WebMethod
    @ResponseWrapper(localName = "feedMeResponse", targetNamespace = "http://server.streamreceiving.mtom.demo/", className = "demo.mtom.streamsending.client.stubs.FeedMeResponse")
    public java.lang.String feedMe(
        @WebParam(name = "arg0", targetNamespace = "")
        demo.mtom.streamsending.client.stubs.BigDataRequest arg0
    ) throws IOException_Exception;
}
