
package demo.mtom.streamsending.client.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Tue May 08 16:54:52 CEST 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "IOException", targetNamespace = "http://server.streamreceiving.mtom.demo/")
public class IOException_Exception extends Exception {
    public static final long serialVersionUID = 20120508165452L;
    
    private demo.mtom.streamsending.client.stubs.IOException ioException;

    public IOException_Exception() {
        super();
    }
    
    public IOException_Exception(String message) {
        super(message);
    }
    
    public IOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, demo.mtom.streamsending.client.stubs.IOException ioException) {
        super(message);
        this.ioException = ioException;
    }

    public IOException_Exception(String message, demo.mtom.streamsending.client.stubs.IOException ioException, Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

    public demo.mtom.streamsending.client.stubs.IOException getFaultInfo() {
        return this.ioException;
    }
}
